# Generated by Django 5.0.1 on 2024-01-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPC_Genero', models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino'), ('3', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPC_Ocupacion', models.CharField(choices=[('1', 'Dueña de Casa'), ('2', 'Trabajadora'), ('3', 'Desempleada'), ('4', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPC_SistemaSalud', models.CharField(choices=[('1', 'Fonasa'), ('2', 'Isapre'), ('3', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OPC_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPC_Respuesta', models.CharField(max_length=200)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anioNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('id_usuario', models.IntegerField()),
                ('Comuna_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.comuna')),
                ('Genero_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.genero')),
                ('Ocupacion_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.ocupacion')),
                ('SistemaSalud_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.sistemasalud')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField(auto_now_add=True)),
                ('id_opc_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opc_respuesta')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregunta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.usuario')),
            ],
        ),
    ]
