# Generated by Django 5.0.1 on 2024-01-15 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Fecha_Ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
