# Generated by Django 5.0.1 on 2024-01-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0002_usuario_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='pregunta',
            new_name='Texto_Pregunta',
        ),
    ]
