# Generated by Django 5.0.1 on 2024-01-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0003_rename_pregunta_pregunta_texto_pregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Texto_Pregunta',
            new_name='pregunta',
        ),
    ]
