# Generated by Django 5.0.1 on 2024-01-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0006_alter_usuario_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestausuario',
            name='id_opc_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.opc_respuesta'),
        ),
        migrations.AlterField(
            model_name='respuestausuario',
            name='id_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botApp.pregunta'),
        ),
    ]
