# Generated by Django 5.0.1 on 2024-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0007_alter_respuestausuario_id_opc_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestausuario',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
