# Generated by Django 5.0.1 on 2024-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0008_alter_respuestausuario_fecha_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='pruebaApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='genero',
            name='OPC_Genero',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='OPC_Ocupacion',
            field=models.CharField(choices=[('Dueña de Casa', 'Dueña de Casa'), ('Trabajadora', 'Trabajadora'), ('Desempleada', 'Desempleada'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sistemasalud',
            name='OPC_SistemaSalud',
            field=models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
