# Generated by Django 5.0.1 on 2024-01-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0009_pruebaapi_alter_genero_opc_genero_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pruebaApi',
            new_name='Prueba',
        ),
    ]
