# Generated by Django 5.0.1 on 2024-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0011_delete_prueba_remove_respuestausuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='respuestausuario',
            old_name='id_manychat',
            new_name='Id_manychat',
        ),
    ]
