# Generated by Django 5.0.1 on 2024-01-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0012_prueba_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
