# Generated by Django 5.0.1 on 2024-01-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0013_delete_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestausuario',
            old_name='Id_manychat',
            new_name='id_manychat',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Id_manychat',
            new_name='id_manychat',
        ),
    ]
