# Generated by Django 5.0.1 on 2024-01-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0014_rename_id_manychat_respuestausuario_id_manychat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPC_Respuesta',
            new_name='PreguntaOpcionRespuesta',
        ),
    ]
