# Generated by Django 5.0.1 on 2024-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0017_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario'),
        ),
    ]
