# Generated by Django 5.0.1 on 2024-01-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0018_alter_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariorespuesta',
            name='id_pregunta',
        ),
    ]
