# Generated by Django 5.0.1 on 2024-01-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0019_remove_usuariorespuesta_id_pregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariorespuesta',
            old_name='id_manychat',
            new_name='id_usuario',
        ),
    ]
