# Generated by Django 5.0.1 on 2024-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0021_alter_comuna_id_alter_genero_id_alter_ocupacion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariorespuesta',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuariorespuesta',
            name='Rut',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
