# Generated by Django 5.0.1 on 2024-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0022_remove_usuariorespuesta_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTextoPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Texto Pregunta')),
                ('Rut', models.CharField(max_length=10)),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('fecha_pregunta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
