# Generated by Django 5.0.1 on 2024-02-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0025_mitabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiTabla',
        ),
    ]
