# Generated by Django 5.0.1 on 2024-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0026_delete_mitabla'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiTabla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Texto')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
    ]
