# Generated by Django 5.0.1 on 2024-02-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0028_mitabla_genero_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiTabla',
            new_name='MensajeContenido',
        ),
    ]
